FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore unit-converter.csproj

RUN dotnet publish unit-converter.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 5158

ENV ASPNETCORE_URLS=http://+:5158

ENTRYPOINT ["dotnet", "unit-converter.dll"]